language: python

matrix:
  include:
    - python: 3.5
      env:
        - COVERAGE=false
    - python: 3.6
      env:
        - COVERAGE=true

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - cp pygridtools/testing/matplotlibrc .

install:
  # We just set up a conda environment with the right Python version. This
  # should not need changing.
  - conda create --yes --channel=conda-forge --name=test python=$TRAVIS_PYTHON_VERSION pygridgen fiona geopandas scipy matplotlib pytest pytest-mpl pytest-cov pytest-pep8 coverage docopt requests pyyaml
  - source activate test
  - pip install codecov


script:
  - coverage run --source pygridtools check_pygridtools.py --cov --verbose --pep8

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      codecov;
    fi

