language: python

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=true
    - python: 3.3
      env:
        - COVERAGE=false
    - python: 3.4
      env:
        - COVERAGE=false

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - cp testing/matplotlibrc .

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda config --add channels phobson
  - conda config --add channels JimInCO

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.

  - conda install --yes seaborn bokeh fiona nose
  - conda install --yes pygridgen
  - pip install coveralls

script:
  - nosetests --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then coveralls fi
