# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run basic unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
        # the create command looks like this:
        micromamba-version: '2.0.2-2'
        environment-name: test-env
        create-args: >-
          python=${{ matrix.python-version }}
          gridgen
          shapely
          fiona
          geopandas
          scipy
          matplotlib
          ipywidgets
          pytest
          pytest-mpl
          pytest-cov
          pytest-pep8
          coverage
          docopt
          requests
          pyyaml
          pygridgen
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    - name: Run Python tests
      run: python check_pygridtools.py --verbose --durations=10 --strict
      shell: bash -el {0}
